name: generate animation

on:
  # Se ejecuta autom√°ticamente cada 24 horas
  schedule:
    - cron: "0 0 * * *" 
  
  # Permite ejecutarlo manualmente en cualquier momento
  workflow_dispatch:
  
  # Se ejecuta cada vez que haces un push en la rama principal
  push:
    branches:
    - main
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Genera el juego de la serpiente a partir de las contribuciones del usuario
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: miguelfv99
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Sube el contenido de la carpeta 'dist' a una rama llamada 'output'
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
